# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: CpoyFiles@1
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
     SourceFolder: '$(build.sourcedirectory)'
     Contents: |
      **\bin\$(BuildConfiguration)\**
      src\*.testsettings
     TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailded()

- task: PublishBuildArtifact@1
  displayname: 'Publish Artifact: drop'
  inputs:
   PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
